name: oracle
services:
  db:
    image: oracle/database:18.4.0-xe
    hostname: oracle
    working_dir: /opt/oracle
    volumes:
      - ./db/opt/oracle/oradata/:/opt/oracle/oradata/
    environment:
      - ORACLE_PWD=Passw0rd
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 3G
